ProjetoConta/ContaWeb/Models/ErrorViewModel.cs
using System;

namespace ContaWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjetoConta/ContaWeb/Controllers/ContaController.cs
using ContaDomain.Entities;
using ContaRepository.Interfaces;
using ContaRepository.Repository;
using Microsoft.AspNetCore.Mvc;

namespace ContaWeb.Controllers
{
    public class ContaController : Controller
    {
        private IContaRepository repositoryConta;

        private IImovelRepository repositoryImovel;

        public ContaController(IContaRepository repositoryConta, IImovelRepository repositoryImovel)
        {
            this.repositoryConta = repositoryConta;
            this.repositoryImovel = repositoryImovel;
        }
        public IActionResult Index()
        {        
            var contas = repositoryConta.Getall();
            ViewBag.maiorConsumo = repositoryConta.GetMaiorConsumo();
            ViewBag.menorConsumo = repositoryConta.GetMenorConsumo();
            return View(contas);
        }

        public IActionResult Imovel()
        {
            var imoveis = repositoryImovel.Getall();
            return View();
        }

        public IActionResult Create()
        {
            ViewBag.ImoveisConta = repositoryImovel.Getall();
            return View();
        }

        [HttpPost]
        public IActionResult Create(ContaLuz conta)
        {
            conta.imovel = repositoryImovel.GetById(conta.imovel.id);
            repositoryConta.Create(conta);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            ViewBag.ImoveisConta = repositoryImovel.Getall();
            var conta = repositoryConta.GetById(id);
            return View(conta);
        }

        [HttpPost]
        public IActionResult Edit(ContaLuz conta)
        {
            conta.imovel = repositoryImovel.GetById(conta.imovel.id);
            repositoryConta.Update(conta);
            return RedirectToAction("Index");
        }   

        public IActionResult Delete(int id)
        {
            repositoryConta.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

ProjetoConta/ContaWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ContaWeb.Models;
using Microsoft.AspNetCore.Mvc;

namespace ContaWeb.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjetoConta/ContaWeb/Controllers/ImovelController.cs
using ContaDomain.Entities;
using ContaRepository.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace ContaWeb.Controllers
{
    public class ImovelController : Controller
    {
        private IImovelRepository repositoryImovel;
        
        public ImovelController(IImovelRepository repositoryImovel)
        {
            this.repositoryImovel = repositoryImovel;
        }
        public IActionResult Index()
        {
            var imoveis = repositoryImovel.Getall();
            return View(imoveis);
        }

        public IActionResult CreateImovel()
        {
            return View();
        }
            
        [HttpPost]
        public IActionResult CreateImovel(Imovel imovel)
        {
            repositoryImovel.Create(imovel);
             return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var imovel = repositoryImovel.GetById(id);
            return View(imovel);
        }

        [HttpPost]
        public IActionResult Edit(Imovel imovel)
        {
           
            repositoryImovel.Update(imovel);
            return RedirectToAction("Index");
        }
        
        public IActionResult Delete(int id)
        {
            repositoryImovel.Delete(id);
            return RedirectToAction("Index");
        }

    }
}

ProjetoConta/ContaWeb/Views/Conta/Create.cshtml
@model ContaDomain.Entities.ContaLuz

<div class="form-horizontal">
    <form action="Create" method="Post">

        <div class="form-group">
            <label>Id</label>
            <input  class="form-control"
                    type="text" name="id"/>
        </div>

        <div class="form-group">
            <label>Data Leitura</label>
            <input  class="form-control"
                    type="date" name="DataLeitura"/>
        </div>

        <div class="form-group">
            <label>Numero Leitura</label>
            <input  class="form-control"
                    type="text" name="NumLeitura"/>
        </div>
        <div class="form-group">
            <label>Quantidade de Kw</label>
            <input  class="form-control"
                    type="text" name="KwGasto"/>
        </div>
        <div class="form-group">
            <label>Valor da Conta</label>
            <input  class="form-control"
                    type="text" name="ValorAPagar"/>
        </div>
        <div class="form-group">
            <label>Data do Pagamento</label>
            <input  class="form-control"
                    type="date" name="DataPagamento"/>
        </div>

        <div class="form-group">
            <label>Media de Consumo</label>
            <input  class="form-control"
                    type="text" name="MediaConsumo"/>
        </div>

        <div class="form-group"> 
            <label for="imovel">Cidade</label>
            <select class="form-control" name="imovel.id" required>
                <option value="" disabled selected>Selecione o Imovel</option>
            @foreach(var imovel in ViewBag.ImoveisConta)
            {
                <option value="@imovel.id">@imovel.id | @imovel.Cidade</option>
            }
            </select>   

        </div>

        <input  class="btn btn-primary" 
                type="submit" value="Salvar"/>
    </form>
</div>

ProjetoConta/ContaWeb/Views/Conta/Edit.cshtml
@model ContaDomain.Entities.ContaLuz


<div class="form-horizontal">
    <form action="Edit" method="Post">
        
        <input hidden type="text" name="id" id="id" value="@Model.id"/>

        <div class="form-group">
            <label>Data Leitura</label>
            
            <div class="editor-field">
                @Html.EditorFor(model => model.DataLeitura, new { htmlAttributes = new { @class = "form-control"} })
                <small class="form-text text-muted ">@Html.ValidationMessageFor(model => model.DataLeitura)</small>
            </div>
        </div>

        <div class="form-group">
            <label>Numero Leitura</label>
            <input  class="form-control"
                    type="text" name="NumLeitura"
                    value="@Model.NumLeitura"/>
        </div>
        <div class="form-group">
            <label>Quantidade de Kw</label>
            <input  class="form-control"
                    type="text" name="KwGasto"
                    value="@Model.KwGasto"/>
        </div>
        <div class="form-group">
            <label>Valor da Conta</label>
            <input  class="form-control"
                    type="text" name="ValorAPagar"
                    value="@Model.ValorAPagar"/>
        </div>
        <div class="form-group">
            <label>Data do Pagamento</label>
            <div class="editor-field">
                @Html.EditorFor(model => model.DataPagamento, new { htmlAttributes = new { @class = "form-control"} })
                <small class="form-text text-muted">@Html.ValidationMessageFor(model => model.DataPagamento)</small>
            </div>
        </div>

        <div class="form-group">
            <label>Media de Consumo</label>
            <input  class="form-control"
                    type="text" name="MediaConsumo"
                    value="@Model.MediaConsumo"/>
        </div>

        <div  class="form-group">
            <label for="imovel">Cidade</label>
            <select class="form-control" name="imovel.id" required>
                    <option value="" disabled>Selecione a Cidade</option>
                @foreach(var imovel in ViewBag.ImoveisConta ){
                    <!option value="@imovel.id" selected="@(@imovel.id == Model.imovel.id)">@imovel.Cidade</!option>
                }
            </select>
        </div>

        <input  class="btn btn-primary" 
                type="submit" value="Salvar"/>

    </form>
</div>

ProjetoConta/ContaWeb/Views/Conta/Index.cshtml
@model IEnumerable<ContaDomain.Entities.ContaLuz>

</br></br>
<a href="Conta/Create" class="btn btn-primary">Nova Conta</a>
</br></br>

<div class="container">
    <div class="row"> 
        <div class="col-sm-12" >  
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Data Leitura</th>
                        <th>Numero Leitura</th>
                        <th>Quantidade Kw</th>
                        <th>Valor Conta</th>
                        <th>Data Pagamento</th>
                        <th>Media de Consumo</th>
                        <th>Cidade</th>
                        <th>Deletar</th>
                        <th>Editar</th>
                    </tr>
                </thead>
                @foreach(var item in Model)
                {
                    <tr>
                        <td>@item.id</td>
                        <td>@item.DataLeitura</td>
                        <td>@item.NumLeitura</td>
                        <td>@item.KwGasto</td>
                        <td>@item.ValorAPagar</td>
                        <td>@item.DataPagamento</td>
                        <td>@item.MediaConsumo</td>
                        <td>@item.imovel.Cidade</td>
                        <td><a class="btn btn-danger"
                            href="Conta/Delete/@item.id">Delete</a> </td>
                        <td><a class="btn btn-primary" 
                            href="Conta/Edit/@item.id">Editar</a> </td>
                    </tr>
                }
            </table>
        </div>  
        <div class="col-sm-12">
            <h3>Maior Consumo</h3>
            <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Data Leitura</th>
                    <th>Numero Leitura</th>
                    <th>Quantidade Kw</th>
                    <th>Valor Conta</th>
                    <th>Data Pagamento</th>
                    <th>Media de Consumo</th>
                    <th>Cidade</th>
                </tr>
            </thead>
            @if(ViewBag.maiorConsumo != null)
                {      
                <tr>
                   
                    <td>@ViewBag.maiorConsumo.id</td>
                    <td>@ViewBag.maiorConsumo.DataLeitura</td>
                    <td>@ViewBag.maiorConsumo.NumLeitura</td>
                    <td>@ViewBag.maiorConsumo.KwGasto</td>
                    <td>@ViewBag.maiorConsumo.ValorAPagar</td>
                    <td>@ViewBag.maiorConsumo.DataPagamento</td>
                    <td>@ViewBag.maiorConsumo.MediaConsumo</td>
                    <td>@ViewBag.maiorConsumo.imovel.Cidade</td>
                </tr>
                }
        </table>
        </div>    
        <div class="col-sm-12">
            <h3>Menor Consumo</h3>
            <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Data Leitura</th>
                    <th>Numero Leitura</th>
                    <th>Quantidade Kw</th>
                    <th>Valor Conta</th>
                    <th>Data Pagamento</th>
                    <th>Media de Consumo</th>
                    <th>Cidade</th>
                </tr>
            </thead>
            @if(ViewBag.maiorConsumo != null)
                { 
                <tr>
                    <td>@ViewBag.menorConsumo.id</td>
                    <td>@ViewBag.menorConsumo.DataLeitura</td>
                    <td>@ViewBag.menorConsumo.NumLeitura</td>
                    <td>@ViewBag.menorConsumo.KwGasto</td>
                    <td>@ViewBag.menorConsumo.ValorAPagar</td>
                    <td>@ViewBag.menorConsumo.DataPagamento</td>
                    <td>@ViewBag.menorConsumo.MediaConsumo</td>
                    <td>@ViewBag.menorConsumo.imovel.Cidade</td>
                </tr>
                }
        </table>
        </div>      
    </div> 
</div>

ProjetoConta/ContaWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProjetoConta/ContaWeb/Views/Imovel/CreateImovel.cshtml
@model ContaDomain.Entities.Imovel

<div class="form-horizontal">
    <form action="CreateImovel" method="Post">

        <div class="form-group">
            <label>Id</label>
            <input  class="form-control"
                    type="text" name="id"/>
        </div>

        <div class="form-group">
            <label>Identificação</label>
            <input  class="form-control"
                    type="text" name="Identificacao"/>
        </div>

        <div class="form-group">
            <label>Numero</label>
            <input  class="form-control"
                    type="text" name="Numero"/>
        </div>
        <div class="form-group">
            <label>Bairro</label>
            <input  class="form-control"
                    type="text" name="Bairro"/>
        </div>
        <div class="form-group">
            <label>Cidade</label>
            <input  class="form-control"
                    type="text" name="Cidade"/>
        </div>
        <div class="form-group">
            <label>Estado</label>
            <input  class="form-control"
                    type="text" name="Estado"/>
        </div>

        <input  class="btn btn-primary" 
                type="submit" value="Salvar"/>
    </form>
</div>

ProjetoConta/ContaWeb/Views/Imovel/Edit.cshtml
@model ContaDomain.Entities.Imovel


<div class="form-horizontal">
    <form action="Edit" method="Post">
        
        <input hidden type="text" name="id" id="id" value="@Model.id"/>

        <div class="form-group">
            <label>Identificaçãp</label>
            <input  class="form-control"
                    type="text" name="Identificacao"
                    value="@Model.Identificacao"/>
        </div>

        <div class="form-group">
            <label>Numero</label>
            <input  class="form-control"
                    type="text" name="Numero"
                    value="@Model.Numero"/>
        </div>
        <div class="form-group">
            <label>Bairro</label>
            <input  class="form-control"
                    type="text" name="Bairro"
                    value="@Model.Bairro"/>
        </div>
        <div class="form-group">
            <label>Cidade</label>
            <input  class="form-control"
                    type="text" name="Cidade"
                    value="@Model.Cidade"/>
        </div>

        <div class="form-group">
            <label>Estado</label>
            <input  class="form-control"
                    type="text" name="Estado"
                    value="@Model.Estado"/>
        </div>

        <input  class="btn btn-primary" 
                type="submit" value="Salvar"/>

    </form>
</div>

ProjetoConta/ContaWeb/Views/Imovel/Index.cshtml
@model IEnumerable<ContaDomain.Entities.Imovel>


<a href="Imovel/CreateImovel" class="btn btn-primary">Novo Imovel</a>
</br></br>

<div class="container">
    <div class="row"> 
        <div class="col-sm-12" >  
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Identificação</th>
                        <th>Numero</th>
                        <th>Bairro</th>
                        <th>Cidade</th>
                        <th>Estado</th>                        
                        <th>Editar</th>
                    </tr>
                </thead>

                @foreach(var Imoveis in Model)
                {
                    <tr>
                        <td>@Imoveis.id</td>
                        <td>@Imoveis.Identificacao</td>
                        <td>@Imoveis.Numero</td>
                        <td>@Imoveis.Bairro</td>
                        <td>@Imoveis.Cidade</td>
                        <td>@Imoveis.Estado</td>
                        <td><a class="btn btn-danger"
                            href="Imovel/Delete/@Imoveis.id">Delete</a> </td>
                        <td><a class="btn btn-primary" 
                            href="Imovel/Edit/@Imoveis.id">Editar</a> </td>
                        
                    </tr>
                }
            </table>
        </div>   
    </div> 
</div>

ProjetoConta/ContaWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ContaWeb</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ContaWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Conta" asp-action="Index">Conta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Imovel" asp-action="Index">Imovel</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ContaWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>